name = "Wavelets"
uuid = "29a6e085-ba6d-5f35-a997-948ac2efa89a"
author = ["Gudmundur Adalsteinsson"]
version = "0.10.0"

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DSP = "0.5.1, 0.6, 0.7"
FFTW = "0.3, 1"
Reexport = "0.2, 1.0"
SpecialFunctions = "0.7.1, 0.8, 0.9, 0.10, 1, 2"
Statistics = "1"
julia = "1"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DelimitedFiles"]
